[package]
name = "fast-voxel-perprocessor"
version = "0.1.0"
edition = "2021"

[dependencies]
fast-voxel-lib = { path = "../fast-voxel-lib" }

log = "0.4.22"
env_logger = "*"
clap = { version = "*", features = ["derive"]}